version: '3'

services:
  db:
    image: postgres
  web:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    env_file: ../.env
    ports:
      - "8000:8000"
    depends_on:
      - db
